version: 2.1

orbs:
  cypress: cypress-io/cypress@1.29.0

workflows:
  build:
    jobs:
      - cypress/install:
        build: 'yarn install'
      - cypress/run:
          yarn: true
          requires:
            - cypress/install
