version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.2

jobs:
  build:
    docker:
      - image: cypress/base:14.16.0
      - image: 'cimg/node:15.0.1-browsers'
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --interactive
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache ## cache both yarn and Cypress!
      - browser-tools/install-browser-tools
      - run:
          name: 'Run tests on chrome'
          command: $(yarn bin)/cypress run --browser chrome
      - run:
          name: 'Run tests on firefox'
          command: $(yarn bin)/cypress run --browser firefox
      - run:
          name: 'Run tests on edge'
          command: $(yarn bin)/cypress run --browser edge
