version: 2.1

jobs:
  build:
    docker:
      - image: cypress/browsers:node14.17.0-chrome91-ff89
        environment:
          ## this enables colors in the output
          TERM: xterm
      - image: cypress/browsers:node14.10.1-edge88
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache ## cache both yarn and Cypress!
      - run:
          name: 'Run tests on chrome'
          command: $(yarn bin)/cypress run --browser chrome
      - run:
          name: 'Run tests on firefox'
          command: $(yarn bin)/cypress run --browser firefox
      - run:
          name: 'Run tests on edge'
          command: $(yarn bin)/cypress run --browser edge
